server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HealthHubUsers?createDatabaseIfNotExist=true
    username: root
    password: imanbello
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
